# Generated by Django 5.1.5 on 2025-02-05 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_pessoa_atualizado_em_pessoa_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data/hora Criação')),
                ('lei', models.CharField(max_length=255, verbose_name='Lei')),
                ('artigo', models.CharField(max_length=255, verbose_name='Artigo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data/hora Criação')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastro.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='infracoes',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='cadastro.infracao'),
        ),
    ]
